application: bhs-stem
version: 1
api_version: 1
runtime: python27
threadsafe: no

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
